-- ==============================================================================
-- eMarket247 Product Catalogue Seed Data
-- Generated from the paired EN/BN catalogue records.
-- Prices, materials, stock state and quantities stay NULL until owner-approved.
-- Published slugs are preserved exactly.
-- ==============================================================================

SET NAMES utf8mb4;

-- Initial import of the 30 currently published product identities.
-- This seed is intentionally not an upsert: rerunning it must not overwrite
-- product facts later approved and maintained through the admin/database.
INSERT INTO `emk_products`
  (`sku`, `slug`, `title_en`, `title_bn`, `category`, `price`,
   `is_price_pending`, `material`, `stock_status`, `stock_qty`,
   `lead_en`, `lead_bn`, `image_url`, `is_active`)
VALUES
  ('EMK-RING-001', 'emarket247-jewellery-detail-01', 'Interwoven Gold-Tone Ring', 'বুনন নকশার সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-interwoven-pattern-ring.webp', 1),
  ('EMK-SET-006', 'emarket247-jewellery-detail-06', 'Stone-Detail Gold-Tone Earrings & Pendant Set', 'স্টোন-ডিটেইল সোনালি কানের দুল ও লকেট সেট', 'Jewellery Sets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-stone-detail-set-09.webp', 1),
  ('EMK-SET-007', 'emarket247-jewellery-detail-07', 'Circle-Motif Gold-Tone Jewellery Set', 'বৃত্ত-নকশার সোনালি জুয়েলারি সেট', 'Jewellery Sets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-circle-jewellery-set-07.webp', 1),
  ('EMK-RING-010', 'emarket247-jewellery-detail-10', 'Lattice Dome Gold-Tone Ring', 'জালি-গম্বুজ সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-lattice-dome-ring.webp', 1),
  ('EMK-RING-011', 'emarket247-jewellery-detail-11', 'Infinity Crossed-Band Gold-Tone Ring', 'ইনফিনিটি ক্রস-ব্যান্ড সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-infinity-crossed-band-ring.webp', 1),
  ('EMK-RING-012', 'emarket247-jewellery-detail-12', 'Heart Gold-Tone Ring Pair', 'হৃদয় সোনালি আংটি জোড়া', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-heart-ring-pair.webp', 1),
  ('EMK-RING-013', 'emarket247-jewellery-detail-13', 'Double-Heart Gold-Tone Ring', 'ডাবল-হার্ট সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-double-heart-ring.webp', 1),
  ('EMK-BRAC-014', 'emarket247-bracelets-14', 'Braided Link-Chain Gold-Tone Bracelet', 'বিনুনি লিঙ্ক-চেইন সোনালি ব্রেসলেট', 'Bracelets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-braided-link-chain-bracelet.webp', 1),
  ('EMK-BRAC-016', 'emarket247-necklaces-16', 'Floral Charm-Chain Gold-Tone Bracelet', 'ফুলেল চার্ম-চেইন সোনালি ব্রেসলেট', 'Bracelets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-floral-charm-chain.webp', 1),
  ('EMK-NECK-017', 'emarket247-bangles-17', 'Floral Drop Gold-Tone Necklace', 'ফুলেল ড্রপ সোনালি হার', 'Necklaces', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-floral-gold-tone-necklace-04.webp', 1),
  ('EMK-BRAC-018', 'emarket247-bangles-18', 'Floral Station Gold-Tone Bracelet', 'ফুলেল স্টেশন সোনালি ব্রেসলেট', 'Bracelets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-floral-gold-tone-bracelet-18.webp', 1),
  ('EMK-RING-019', 'emarket247-bangles-19', 'Geometric Signet Gold-Tone Ring', 'জ্যামিতিক সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-geometric-gold-tone-ring-19.webp', 1),
  ('EMK-BANG-020', 'emarket247-bangles-20', 'Textured Gold-Tone Bangle Pair', 'টেক্সচারড সোনালি চুড়ি জোড়া', 'Bangles', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-bangles-08.webp', 1),
  ('EMK-BANG-021', 'emarket247-bangles-21', 'Baguette Screw-Motif Gold-Tone Bangle Pair', 'ব্যাগেট স্ক্রু-মোটিফ সোনালি চুড়ি জোড়া', 'Bangles', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-cross-band-bangle-10.webp', 1),
  ('EMK-RING-022', 'emarket247-bangles-22', 'Petite Detail Gold-Tone Ring', 'ছোট নকশার সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-womens-gold-tone-ring-01.webp', 1),
  ('EMK-SET-023', 'emarket247-bangles-23', 'Pearl-Style Gold-Tone Earrings & Pendant Set', 'পার্ল-স্টাইল সোনালি কানের দুল ও লকেট সেট', 'Jewellery Sets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-pearl-style-gold-tone-set-06.webp', 1),
  ('EMK-RING-024', 'emarket247-bangles-24', 'Triple-Bead Gold-Tone Ring', 'ত্রি-পুঁতি সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-triple-bead-ring-12.webp', 1),
  ('EMK-BANG-025', 'emarket247-bangles-25', 'Slim Baguette Gold-Tone Bangle Pair', 'স্লিম ব্যাগেট সোনালি চুড়ি জোড়া', 'Bangles', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-crossed-band-bangle-11.webp', 1),
  ('EMK-RING-026', 'emarket247-bangles-26', 'Floral Detail Gold-Tone Ring', 'ফুলেল নকশার সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-detail-ring-14.webp', 1),
  ('EMK-RING-027', 'emarket247-bangles-27', 'Floral Gold-Tone Ring', 'ফুলেল সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-floral-ring-13.webp', 1),
  ('EMK-RING-028', 'emarket247-bangles-28', 'Floral Cluster Gold-Tone Ring', 'ফুল-গুচ্ছ সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-floral-ring-16.webp', 1),
  ('EMK-BANG-029', 'emarket247-bangles-29', 'Engraved Open Gold-Tone Bangle', 'খোদাই করা খোলা সোনালি চুড়ি', 'Bangles', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-engraved-open-bangle.webp', 1),
  ('EMK-BANG-030', 'emarket247-bangles-30', 'Ornate Open Gold-Tone Bangle', 'কারুকাজ করা খোলা সোনালি চুড়ি', 'Bangles', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-ornate-open-bangle.webp', 1),
  ('EMK-SET-031', 'emarket247-jewellery-detail-31', 'Teardrop Gold-Tone Earrings & Pendant Set', 'জলবিন্দু সোনালি কানের দুল ও লকেট সেট', 'Jewellery Sets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-teardrop-set-05.webp', 1),
  ('EMK-SET-032', 'emarket247-earrings-32', 'Square Gold-Tone Earrings & Pendant Set', 'চৌকো সোনালি কানের দুল ও লকেট সেট', 'Jewellery Sets', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-earrings-pendant-set-03.webp', 1),
  ('EMK-NECK-046', 'emarket247-necklaces-46', 'Beaded Charm-Chain Gold-Tone Necklace', 'পুঁতির চার্ম-চেইন সোনালি হার', 'Necklaces', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-beaded-charm-chain.webp', 1),
  ('EMK-NECK-047', 'emarket247-necklaces-47', 'Dangling-Bead Statement Gold-Tone Necklace', 'ঝুলন্ত-পুঁতি স্টেটমেন্ট সোনালি হার', 'Necklaces', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-dangling-bead-statement-necklace.webp', 1),
  ('EMK-NECK-049', 'emarket247-floral-trio-gold-tone-necklace', 'Floral Trio Gold-Tone Necklace', 'তিন-ফুলের সোনালি হার', 'Necklaces', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-floral-gold-tone-necklace-02.webp', 1),
  ('EMK-RING-050', 'emarket247-gold-floral-openwork-ring', 'Openwork Floral Gold-Tone Ring', 'খোলা-নকশার ফুলেল সোনালি আংটি', 'Rings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-floral-openwork-ring.webp', 1),
  ('EMK-EARR-051', 'emarket247-gold-tone-teardrop-hoop-earrings', 'Teardrop Stone-Link Gold-Tone Hoop Earrings', 'জলবিন্দু স্টোন-লিংক সোনালি হুপ কানের দুল', 'Earrings', NULL, 1, NULL, NULL, NULL, 'Catalog record in preparation. Specifications, price, and availability are pending approval.', 'ক্যাটালগ রেকর্ড প্রস্তুত হচ্ছে। স্পেসিফিকেশন, মূল্য ও প্রাপ্যতা অনুমোদনের অপেক্ষায়।', '/assets/images/products/emarket247-gold-tone-teardrop-hoop-earrings-15.webp', 1);
